from pydantic import BaseModel
from typing import List,ClassVar,Dict


class DatColumn(BaseModel):
    C_VAR1: ClassVar[List[str]] = [
        "Record Type", "Sec Symbol", "Sec Series", "ISIN", "Security VAR", "Filler",
        "VAR Margin", "Extreme Loss Rate", "Additional Margin", "Daily Margin Rate"
    ]

    DP37: ClassVar[Dict[str, List[str]]] = {
        "01": [
            "PLEDGE SEQ NUMB (PSN)", "PLEDGOR BO ID", "FIRST HOLDER’S FIRST NAME",
            "SECOND HOLDER’S FIRST NAME", "THIRD HOLDER’S FIRST NAME", "PLEDGOR DP’s INTERNAL REFERENCE NO",
            "PLEDGEE BO ID", "PLEDGEE FIRST HOLDER’S FIRST NAME", "PLEDGEE SECOND HOLDER’S FIRST NAME",
            "PLEDGEE THIRD HOLDER’S FIRST NAME", "PLEDGEE DP’s INTERNAL REFERENCE NO",
            "PLEDGE STATUS", "VERIFY FLAG", "ISIN", "ISIN SHORT NAME", "PLEDGE QUANTITY",
            "PLEDGE VALUE", "PLEDGE SET-UP DATE", "PLEDGOR VERIFICATION DATE",
            "PLEDGE ACCEPTANCE DATE", "PLEDGEE VERIFICATION DATE", "REVERSAL DATE",
            "PLEDGE CLOSE DATE", "PLEDGE EXPIRY DATE", "TOTAL UNPLEDGE QUANTITY",
            "TOTAL CONFISCATE DATE", "PLEDGE REMARKS", "FREE LOCKIN FLAG", "LOCKIN ID",
            "LOCKIN EXPIRY DATE", "LOCKIN REASON CODE", "LOCKIN REASON", "AGREEMENT NO",
            "PLEDGE PARENT SEQUENCE NUMBER", "MARGIN PLEDGE RE-PLEDGE IDENTIFIER",
            "MARGIN PLEDGE PARENT SEQUENCE NUMBER", "Exchange ID", "UCC", "Segment ID",
            "CC ID", "CM ID", "TM ID / CP ID", "ENTITY IDENTIFIER"
        ],
        "02": [
            "PLEDGE SEQ NUMB (PSN)", "UNPLEDGE COUNTER", "UNPLEDGE QUANTITY",
            "UNPLEDGE INITIATED BY", "UNPLEDGE STATUS", "UNPLEDGE VERIFY FLAG",
            "UNPLEDGE SETUP DATE", "UNPLEDGE PLEDGOR VERIFICATION DATE",
            "UNPLEDGE ACCEPTANCE/REJECTION DATE", "UNPLEDGE PLEDGEE VERIFICATION DATE",
            "UNPLEDGE REVERSAL DATE", "UPLEDGE REMARKS", "PLEDGOR DP’s INTERNAL REFERENCE NO",
            "PLEDGEE DP’s INTERNAL REFERENCE NO", "MARGIN PLEDGE RE-PLEDGE IDENTIFIER",
            "MARGIN PLEDGE PARENT SEQUENCE NUMBER", "Exchange ID", "UCC", "Segment ID",
            "CC ID", "CM ID", "TM ID / CP ID", "ENTITY IDENTIFIER"
        ],
        "03": [
            "PLEDGE SEQ NUMB (PSN)", "CONFISCATE COUNTER", "CONFISCATE QUANTITY",
            "CONFISCATE STATUS", "CONFISCATE VERIFY FLAG", "CONFISCATE SETUP DATE",
            "CONFISCATE ACCEPTANCE/REJECTION DATE", "CONFISCATE PLEDGEE VERIFICATION DATE",
            "CONFISCATE REVERSAL DATE", "CONFISCATE REMARKS", "PLEDGEE DP’s INTERNAL REFERENCE NO",
            "MARGIN PLEDGE RE-PLEDGE IDENTIFIER", "MARGIN PLEDGE PARENT SEQUENCE NUMBER",
            "Exchange ID", "UCC", "Segment ID", "CC ID", "CM ID", "TM ID / CP ID",
            "ENTITY IDENTIFIER"
        ]
    }
